name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 21.x
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Run lint check
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
      - name: Run prettier check
        uses: borales/actions-yarn@v4
        with:
          cmd: prettier
